version: '3.8'

services:
  postgres-ms-technician-db:
    image: postgres:14.1-alpine
    container_name: postgres-ms-technician-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./applications/app-service/src/main/resources/dbmigration/V1_create_tables.sql:/docker-entrypoint-initdb.d/V1_create_tables.sql
    networks:
      - app-network

  microservice-technician:
    build: .
    environment:
      - POSTGRES_HOST=postgres-ms-technician-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8020:8020"
    depends_on:
      - postgres-ms-technician-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
